# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17d207c4a87fde3cd1e997f93bd828d315fabbc0f528f24b46cf95a25fe9f6918980cfdb87c210b848656f1ed94236cc6e304f714976b630618e46bf7025f781

test:
  secret_key_base: 2312611eb200d8e4011732d9df544e370e790416466c145ddf5810bf4600ab4bbe146b79095617f5dab529b6942764a263d75f1ee5daaa92ca67501309a2b152

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
